apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: ###.###.##.#
    path: /srv/nfs/share/mlflow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coral-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: ###.###.##.#
    path: /srv/nfs/share/coral/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coral-code-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: ###.###.##.#
    path: /srv/nfs/share/coral/code
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coral-checkpoints-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: ###.###.##.#
    path: /srv/nfs/share/coral/checkpoints
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coral-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: ###.###.##.#
    path: /srv/nfs/share/coral/data
